name: Build Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-ci --if-present

  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_CONTAINER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/craftmania-cz/craftbackup:${{ github.run_id }}
            ghcr.io/craftmania-cz/craftbackup:master
            ghcr.io/craftmania-cz/craftbackup:latest
